version: "3.8"

services:
  frontend:
    build:
      context: ../Storage_system_front
      args:
        BASE_URL: http://${HOST_IP}
        API_URL: ${HOST_IP}
        FRONTEND_PORT: ${FRONTEND_PORT}
        BACKEND_PORT: ${BACKEND_PORT}
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
  backend:
    build:
      context: ../Storage_system_back
    ports:
      - "${BACKEND_PORT}:3001"
    environment:
      - MONGO_URI=mongodb://mongo:${MONGODB_PORT}/storage_system
      - FRONTEND_PORT=${FRONTEND_PORT}
      - BACKEND_PORT=${BACKEND_PORT}
      - HOST_IP=${HOST_IP}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: